### ISSUE TITLE
Migrate to Sound null safety

### ISSUE THREAD

**Issue by michalvalkoun** [Emadeddin-eibo/ripple_animation#6]
Hi, it would be great, if you migrate the package to sound null safety.
https://dart.dev/null-safety/unsound-null-safety

**Comment by JacoDuPlooyPoly** [comment]
Hi @Emadeddin-eibo I second this - we're using your lib for a project and it would really be great to have null safety!
I found [this fork](https://github.com/PoloLacoste/ripple_animation) that already implemented null safety, so you could pull form there (specifically check out [this commit](https://github.com/Emadeddin-eibo/ripple_animation/commit/23318dc15598fdf621054d3aaa118114da37786d))
